name: 'jaffle_shop'

config-version: 2
version: '0.1'

profile: 'jaffle_shop'

model-paths: ["jaffle_shop/models"]
seed-paths: ["jaffle_shop/seeds"]
test-paths: ["jaffle_shop/tests"]
analysis-paths: ["jaffle_shop/analysis"]
macro-paths: ["jaffle_shop/macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"
    - "logs"

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  jaffle_shop:
      materialized: table
      staging:
        materialized: view
